"""Add firstname and lastname columns to member table

Revision ID: 088504aa5508
Revises: ccc33b628ab6
Create Date: 2025-12-07 12:56:51.657474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088504aa5508'
down_revision = 'ccc33b628ab6'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add new columns as nullable
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=50), nullable=True))
    
    # Step 2: Migrate existing data - split name into firstname and lastname
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE member 
        SET firstname = CASE 
            WHEN instr(name, ' ') > 0 THEN substr(name, 1, instr(name, ' ') - 1)
            ELSE name
        END,
        lastname = CASE 
            WHEN instr(name, ' ') > 0 THEN substr(name, instr(name, ' ') + 1)
            ELSE ''
        END
    """))
    
    # Step 3: Make columns non-nullable and drop old column
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('firstname', nullable=False)
        batch_op.alter_column('lastname', nullable=False)
        batch_op.drop_index(batch_op.f('idx_member_name'))
        batch_op.drop_column('name')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_active_booking'), sqlite_where=sa.text("status = 'active'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_active_booking'), ['court_id', 'date', 'start_time'], unique=1, sqlite_where=sa.text("status = 'active'"))

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.create_index(batch_op.f('idx_member_name'), ['name'], unique=False)
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
