"""Add payment confirmation request fields to Member

Revision ID: 2696aa995541
Revises: 7b2e60d3d0d4
Create Date: 2026-01-18 11:42:29.984534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2696aa995541'
down_revision = '7b2e60d3d0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_confirmation_requested', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('payment_confirmation_requested_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('payment_confirmation_requested_at')
        batch_op.drop_column('payment_confirmation_requested')

    # ### end Alembic commands ###
