"""Add batch_id to Block model for grouping multi-court blocks

Revision ID: 4acdcc39bec3
Revises: d1e2f3a4b5c6
Create Date: 2026-01-03 01:08:23.726715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acdcc39bec3'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index('idx_block_batch', ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_batch_id'))
        batch_op.drop_index('idx_block_batch')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
