"""Add reservation audit log

Revision ID: 7b2e60d3d0d4
Revises: ee5455c3afaa
Create Date: 2026-01-15 23:00:24.984745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2e60d3d0d4'
down_revision = 'ee5455c3afaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('operation_data', sa.JSON(), nullable=True),
    sa.Column('performed_by_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservation_audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_reservation_audit_operation', ['operation'], unique=False)
        batch_op.create_index('idx_reservation_audit_performed_by', ['performed_by_id'], unique=False)
        batch_op.create_index('idx_reservation_audit_reservation_id', ['reservation_id'], unique=False)
        batch_op.create_index('idx_reservation_audit_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('member_audit_log', schema=None) as batch_op:
        batch_op.alter_column('performed_by_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_audit_log', schema=None) as batch_op:
        batch_op.alter_column('performed_by_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('reservation_audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_reservation_audit_timestamp')
        batch_op.drop_index('idx_reservation_audit_reservation_id')
        batch_op.drop_index('idx_reservation_audit_performed_by')
        batch_op.drop_index('idx_reservation_audit_operation')

    op.drop_table('reservation_audit_log')
    # ### end Alembic commands ###
